"""add room name

Revision ID: ff551b6ef6b7
Revises: c4d3b84e2c4a
Create Date: 2023-05-09 20:39:36.580485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff551b6ef6b7'
down_revision = 'c4d3b84e2c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'name')
    # ### end Alembic commands ###